const Lang_images = {
    python: <img src={require('../assets/python-5.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    clang: <img src={require('../assets/c-1.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    c2lang: <img src={require('../assets/c.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    chash: <img src={require('../assets/c--4.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    javascript: <img src={require('../assets/javascript-1.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    solidity: <img src={require('../assets/solidity.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    postgres: <img src={require('../assets/postgresql.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    reactjs: <img src={require('../assets/react-2.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    nodejs: <img src={require('../assets/nodejs-icon.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    tailwindcss: <img src={require('../assets/tailwind-css-2.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    opencv: <img src={require('../assets/opencv-icon.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    colab: <img src={require('../assets/chrome.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    redux: <img src={require('../assets/redux.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    selenium: <img src={require('../assets/selenium.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    chrome: <img src={require('../assets/chrome.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    html: <img src={require('../assets/html-1.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    css: <img src={require('../assets/css-3.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    java: <img src={require('../assets/java-logo.svg').default} alt="python" className="mx-auto w-10 h-10 object-contain" />,
    mongodb: <img src={require('../assets/mongodb.svg').default} alt="mongodb" className="mx-auto w-10 h-10 object-contain" />,
    rpi: <img src={require('../assets/rpi.svg').default} alt="rpi" className="mx-auto w-10 h-10 object-contain" />,
    microcontroller: <img src={require('../assets/microcontroller.png')} alt="microcontroller" className="mx-auto w-10 h-10 object-contain" />,
    ganache: <img src={require('../assets/ganache-icon.png')} alt="ganache" className="mx-auto w-10 h-10 object-contain" />,
    arduinoide: <img src={require('../assets/arduinoide.png')} alt="arduinoide" className="mx-auto w-10 h-10 object-contain" />,
    socket: <img src={require('../assets/socketio-icon.svg').default} alt="socket" className="mx-auto w-10 h-10 object-contain" />,
    graph: <img src={require('../assets/GraphAPIlogo.png')} alt="graph" className="mx-auto w-10 h-10 object-contain" />,
}

export default Lang_images;